name: Re-enable automerge
on:
  pull_request:
    branches: [main]
    types:
      - auto_merge_disabled
permissions:
  # "permissions" section should not be empty
  # This action doesn't use secrets.GITHUB_TOKEN
  contents: read
jobs:
  main:
    if: "github.event.reason == 'Base branch was modified'"
    runs-on: ubuntu-latest
    steps:
    - name: Update pull request branch
      run: gh api -X PUT "repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/update-branch"
      shell: bash
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    # This prevents pull request from being merged before running a new workflow.
    - name: wait for starting a new workflow by updating branch
      shell: bash
      run: sleep 5

    - name: enable automerge
      shell: bash
      run: gh pr merge --auto --merge "$PR_URL"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}